package generate

import (
	"strings"
	"testing"

	"github.com/HeytalePazguato/plc-gitignore/internal/rules"
)

func TestGitignore_twincat_containsCoreRules(t *testing.T) {
	out := Gitignore(rules.TwinCAT(), Options{Version: "0.0.1"})
	mustContain(t, out, "_Boot/")
	mustContain(t, out, "*.TcLIDs")
	mustContain(t, out, "*.tmc")
	mustContain(t, out, "TwinCAT 3 .gitignore")
	mustContain(t, out, "Generated by plc-gitignore v0.0.1")
}

func TestGitignore_codesys_containsCoreRules(t *testing.T) {
	out := Gitignore(rules.Codesys(), Options{Version: "0.0.1"})
	mustContain(t, out, "*.compileinfo")
	mustContain(t, out, "__pycache__/")
}

func TestGitignore_hmi_includedOnlyWhenRequested(t *testing.T) {
	without := Gitignore(rules.TwinCAT(), Options{Version: "0.0.1"})
	if strings.Contains(without, "TcHmi/www/") {
		t.Error("HMI section should NOT be included without --with-hmi")
	}
	with := Gitignore(rules.TwinCAT(), Options{Version: "0.0.1", WithHMI: true})
	mustContain(t, with, "TcHmi/www/")
}

func TestGitattributes_twincat_containsMergeRules(t *testing.T) {
	out := Gitattributes(rules.TwinCAT(), Options{Version: "0.0.1"})
	mustContain(t, out, "*.tsproj")
	mustContain(t, out, "merge=union")
	mustContain(t, out, "*.plcproj")
}

func TestGitattributes_lfs_includedOnlyWhenRequested(t *testing.T) {
	without := Gitattributes(rules.TwinCAT(), Options{Version: "0.0.1"})
	if strings.Contains(without, "filter=lfs") {
		t.Error("LFS section should NOT be included without --with-lfs")
	}
	with := Gitattributes(rules.TwinCAT(), Options{Version: "0.0.1", WithLFS: true})
	mustContain(t, with, "filter=lfs")
}

func mustContain(t *testing.T, haystack, needle string) {
	t.Helper()
	if !strings.Contains(haystack, needle) {
		t.Errorf("output missing %q", needle)
	}
}
