// Package generate renders RuleSets into the actual .gitignore,
// .gitattributes, and pre-commit hook files written to disk.
package generate

import (
	"fmt"
	"strings"

	"github.com/HeytalePazguato/plc-gitignore/internal/rules"
)

// Options controls optional sections in the generated output.
type Options struct {
	WithHMI bool
	WithLFS bool
	Version string
}

// Gitignore returns the rendered .gitignore content for the given rule set.
func Gitignore(r rules.RuleSet, opts Options) string {
	var b strings.Builder

	writeBanner(&b, fmt.Sprintf("%s .gitignore", r.DisplayName), opts.Version)

	sections := append([]rules.Section(nil), r.Sections...)
	if opts.WithHMI {
		sections = append(sections, r.HMISections...)
	}

	for _, s := range sections {
		b.WriteString("\n")
		b.WriteString(fmt.Sprintf("# --- %s ---\n", s.Title))
		if s.Comment != "" {
			for _, line := range strings.Split(s.Comment, "\n") {
				b.WriteString("# ")
				b.WriteString(line)
				b.WriteString("\n")
			}
		}
		for _, p := range s.Patterns {
			if p.Comment != "" {
				b.WriteString("# ")
				b.WriteString(p.Comment)
				b.WriteString("\n")
			}
			if p.Negate {
				b.WriteString("!")
			}
			b.WriteString(p.Glob)
			b.WriteString("\n")
		}
	}
	return b.String()
}

func writeBanner(b *strings.Builder, title, version string) {
	if version == "" {
		version = "dev"
	}
	b.WriteString("# ==============================================\n")
	b.WriteString("# ")
	b.WriteString(title)
	b.WriteString("\n")
	b.WriteString(fmt.Sprintf("# Generated by plc-gitignore v%s\n", version))
	b.WriteString("# https://github.com/HeytalePazguato/plc-gitignore\n")
	b.WriteString("# ==============================================\n")
}
